---
# defaults file for dns_in_1_check

chroot_etc_d: /var/named/chroot/etc
chroot_named_d: /var/named/chroot/var/named

ssh_d: /etc/ssh
etc_d: /etc

iptables_d: /etc/sysconfig

dns_in_1_files: /etc/ansible/roles/dns_in_1/files
dns_in_1_log: /var/log/ansible/dns_in_1.log
...
