---
# handlers file for dns_out_1_dmz
- name: Restart Named
  service: name=named state=restarted

- name: Restart Sshd
  service: name=sshd state=restarted

- name: Restart Ntp
  service: name=ntpd state=restarted

...


